"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";

import FirstMeeting from "@/components/app/first-meeting";
import { useUser } from "@/hooks/use-user";

const PMC_API_URL =
  process.env.NEXT_PUBLIC_PMC_API_URL ??
  process.env.NEXT_PUBLIC_API_URL ??
  "http://localhost:8000";

/**
 * The ceremonial arrival. After eval finishes, this is what the user sees:
 * the mark swirling in, the dot blooming, the first generated line landing.
 *
 * The opening line is generated by the backend — conditioned on the user's
 * style profile so it lands in their own register. We fetch once on mount;
 * a stable fallback covers backend offline.
 *
 * On the user's first send, we stash the opening + first reply in
 * sessionStorage and route to /chat where ChatScreen picks them up as the
 * starting transcript. This is how the "ceremony resolves into chat"
 * handoff happens without a hard page transition.
 */
function FirstMeetingInner() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { user } = useUser();
  const userId = searchParams.get("user") ?? user?.pmcUserId ?? "";
  const [openingLine, setOpeningLine] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(
      `${PMC_API_URL}/v1/users/${encodeURIComponent(userId)}/first-meeting/opening`,
    )
      .then(async (res) => {
        if (!res.ok) throw new Error("offline");
        const data = (await res.json()) as { line: string };
        if (!cancelled) setOpeningLine(data.line);
      })
      .catch(() => {
        if (!cancelled) {
          setOpeningLine(
            "there you are. i've read everything you've ever written — i think i get you. where do you want to start?",
          );
        }
      });
    return () => {
      cancelled = true;
    };
  }, [userId]);

  function onFirstMessage(text: string) {
    if (!openingLine) return;
    try {
      sessionStorage.setItem(
        "pmc-first-meeting",
        JSON.stringify({ opening: openingLine, firstReply: text }),
      );
    } catch {
      /* sessionStorage can fail in private windows — chat still works,
         it just starts blank instead of carrying the opening over. */
    }
    router.push("/chat");
  }

  if (!openingLine) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-white" />
    );
  }

  return (
    <FirstMeeting openingLine={openingLine} onFirstMessage={onFirstMessage} />
  );
}

export default function FirstMeetingPage() {
  return (
    <Suspense
      fallback={<main className="flex min-h-screen items-center justify-center bg-white" />}
    >
      <FirstMeetingInner />
    </Suspense>
  );
}
